default: &DEFAULT
  # ModelCheckpoint: saves the model after every epoch
  checkpoint_monitor: 'val_loss'  # quantity to monitor (default: 'val_loss')
  checkpoint_verbose: 1 # verbosity mode, 0 or 1 (default: 0)
  checkpoint_save_best_only: True # if True the latest best model according to the quantity
  # monitored will not be overwritten (default: False)
  checkpoint_save_weights_only: True # if True then only the model's weights will be saved, else the
  # full model is saved (default: False)
  checkpoint_mode: 'min'  # one of [auto, min, max], if save_best_only=True the decision to
  # overwrite the current save file is made based on either the maximization or the minimization
  # of the monitored quantity, for 'val_acc' this should be max, for 'val_loss' this should be
  # min, in auto mode the direction is automatically inferred from the name of the monitored
  # quantity (default: 'auto')
  checkpoint_period: 1  # interval (number of epochs) between checkpoints (default: 1)

  # TensorBoard: TensorBoard visualization
  tensorboard_histogram_freq: 1 # frequency (in epochs) at which to compute activation and weight
  # histograms for the layers of the model, if set to 0 histograms won't be computed, validation
  # data (or split) must be specified for histogram visualizations (default: 0)
  tensorboard_write_graph: False  # whether to visualize the graph in TensorBoard, the log file can
  # become quite large when write_graph is set to True (default: True)
  tensorboard_write_grads: True  # whether to visualize gradient histograms in TensorBoard,
  # histogram_freq must be greater than 0 (default: False)
  tensorboard_write_images: False # whether to write model weights to visualize as image in
  # TensorBoard (default: False)
  tensorboard_update_freq: 'epoch'  # 'batch' or 'epoch' or integer, when using 'batch' writes the
  # losses and metrics to TensorBoard after each batch, the same applies for 'epoch', if using an
  # integer (let's say 10000) the callback will write the metrics and losses to TensorBoard every
  # 10000 samples, Note that writing too frequently to TensorBoard can slow down your training
  # (default: 'epoch')

SimpleRNN:
  <<: *DEFAULT
  name: 'SimpleRNN'

GRU:
  <<: *DEFAULT
  name: 'GRU'

LSTM:
  <<: *DEFAULT
  name: 'LSTM'