default: &DEFAULT
  # TRAINING
  num_epochs: 50 # number of iterations to rn the data set through the model
  batch_size: 32  # size of each batch of data that is feed into the model
  learning_rate: 0.0001 # learning rate
  # DATA
  num_classes: 1  # number of classes (binary classification: 0 = not schedulable, 1 = schedulable)
  test_size: 0.2  # procentual number of test examples
  time_steps: 4 # number of time steps = sequence length/size = number of tasks per task-set
  num_features: 9 # number of features per task

LSTM:
  <<: *DEFAULT
  hidden_dim: 32 # size of RNN hidden dimension = hidden state (both c and h)
  keep_prob: 1  # keep probability for dropout wrapper
  num_cells: 1  # number of LSTM cells